### ISSUE TITLE
??

### ISSUE THREAD

**Issue by Radi321** [dqsully/run-lua#2] opened 2015-06-27 09:30 UTC
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Microsoft Windows 8.1
**Thrown From**: [run-lua](https://github.com/dqsully/run-lua) package, v0.1.1
### Stack Trace

Uncaught Error: Can't save buffer with no file path

```
At C:\Users\Radosław\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:983

Error: Can't save buffer with no file path
  at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\Radosław\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:983:15)
  at TextBuffer.module.exports.TextBuffer.save (C:\Users\Radosław\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:978:19)
  at TextEditor.module.exports.TextEditor.save (C:\Users\Radosław\AppData\Local\atom\app-1.0.0\resources\app.asar\src\text-editor.js:579:26)
  at Object.module.exports.RunLua.executeCurrent (C:\Users\Radosław\.atom\packages\run-lua\lib\run-lua.coffee:27:40)
  at atom-workspace.subscriptions.add.atom.commands.add.run-lua:executeCurrent (C:\Users\Radosław\.atom\packages\run-lua\lib\run-lua.coffee:18:90)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Radosław\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:241:29)
  at CommandRegistry.handleCommandEvent (C:\Users\Radosław\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\Radosław\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:156:19)
  at EventEmitter.<anonymous> (C:\Users\Radosław\AppData\Local\atom\app-1.0.0\resources\app.asar\src\window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```
### Commands

```
     -4:48.8.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -4:48.8.0 snippets:expand (atom-text-editor.editor.is-focused)
     -4:48.8.0 editor:indent (atom-text-editor.editor.is-focused)
     -4:46.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:41.7.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -4:41.3.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -4:40.3.0 core:move-right (atom-text-editor.editor.is-focused)
     -4:38.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -4:38.4.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -4:35.9.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -4:32.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:31 core:save (atom-text-editor.editor.is-focused)
     -4:06.3.0 package-generator:generate-syntax-theme (atom-text-editor.editor.is-focused)
     -3:55.7.0 grammar-selector:show (atom-text-editor.editor.is-focused)
  5x -3:41.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -2:31.8.0 run-lua:executeCurrent (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "run-lua": {}
}
```
### Installed Packages

``` coffee
# User
run-lua, v0.1.1
toggle-packages, v1.0.1

# Dev
No dev packages
```

**Comment by dqsully** [comment] 2015-06-27 13:52
I'm on it, thank you for reporting this. The problem is that I opened a path that doesn't exist, so it cannot be saved to. This should be fixed by the end of today (MDT).

**Comment by Radi321** [comment] 2015-06-27 18:51
Thank you for reply ;)

**Comment by dqsully** [comment] 2015-06-27 18:53
I just now made some headway, and am working on a custom version of the 'TextEditor' class, should be much better within the next hour. Do you have any feature requests?

**Comment by dqsully** [comment] 2015-06-27 21:21
I am closing this issue, but you can email me at dqsully@outlook.com.

**Closed as completed by dqsully** 2015-06-27 21:21 UTC
